### ISSUE TITLE
Too much ambiguity

### ISSUE THREAD

**Issue by rbuckton** [EisenbergEffect/yet-another-decorators-proposal#2]
In general I like the approach, but I have some concerns about ambiguity, especially if we consider adding this and possibly expanding it to other things (functions, object literal members, parameters, other decorators, etc.).

Based on the examples in the explainer, I can't tell whether a decorator like this should apply to a class, a method, an accessor, a field, etc:

```js
decorator dec {
  class { }
}
```

It might be better to expand the syntax to be more specific:

```js
decorator NAME PARAMETERS_opt {
  SELECTOR {
    AUGMENTATIONS
    SPECIAL_BLOCKS
  }
  // ... SELECTOR
}
```

A _SELECTOR_ is a specific combination of keywords that determines the allowed target of a decorator and the context of any augmentations:

- _base selectors_ target a specific AST node:
  - `class { ... }` refers to a class declaration/expression:
    - template fields: `${class}`, `${class.name}`, `${constructor.code}`, `${static.code}`
    - augmentations: any class members
    - special blocks: `constructor`, `static`
  - `object { ... }` refers to an object literal:
    - template fields: `${object.code}`
    - augmentations: any object literal members
    - special blocks: `code`
  - `method { ... }` refers to a method or accessor of a class or object literal:
    - template fields: `${method}`, `${method.name}`, `${method.code}`, `${method.isStatic}`
    - augmentations: none
    - special blocks: `code`, `static`
  - `constructor { ... }` refers to the constructor of a class:
    - template fields: `${class}`, `${class.name}`, `${constructor.code}`
    - augmentations: none
    - special blocks: `code`, `static`
  - `field { ... }` refers to a field of a class:
    - template fields: `${field.name}`, `${field.code}`, `${field.isStatic}`
    - augmentations: none
    - special blocks: `code`
  - `property { ... }` refers to the property of an object literal:
    - template fields: `${property.name}`, `${property.code}`
    - augmentations: none
    - special blocks: `code`
  - `function { ... }` refers to a function declaration/expression or arrow function
    - template fields: `${function}`, `${function.name}`, `${function.code}`, `${static.code}`
    - augmentations: none
    - special blocks: `function`, `static`
  - `parameter { ... }` refers to the parameter of a function, method, or constructor:
    - template fields: `${parameter.name}`, `${parameter.code}`
    - augmentations: none
    - special blocks: `code`
- _compound selectors_ use the template fields and special blocks of all included base selectors,
  but only the augmentations of the leftmost selector:
  - `class method { ... }` refers to a method of a class.
  - `class field { ... }` refers to a field of a class.
  - `class method parameter { ... }` refers to a parameter of a class method.
  - `class constructor parameter { ... }` refers to a parameter of a class constructor.
  - `object method { ... }` - refers to a method of an object literal
  - `object property { ... }` - refers to a property of an object literal
  - `function parameter { ... }` - refers to a parameter of a function
- _constraint selectors_ `static`, `nonstatic`, `private`, `non-private`, `get`, and `set` can be used as part of a compound selector to constrain decorator placement:
  - `static` and `nonstatic`: 
    - indicate the target must be a static or non-static member of a class
    - can only follow `class`
    - can only precede `private`, `nonprivate`, `get`, `set`, `field`, or `method`
  - `private` and `nonprivate`:
    - indicate the target must or must not have a private name
    - can only follow `class` or `static`
    - can only precede `get`, `set`, `field`, or `method`
  - `get` and `set`:
    - indicate the target must be a getter or setter.
    - can only follow `class`, `static`, `nonstatic`, `private`, `nonprivate` or `object`.
    - can only precede `method`.

A single decorator can have one or more _SELECTOR_ elements. The first selector matching the node is used, the rest are ignored even if they are more specific.

**Special note regarding *template fields*:** The `name.` prefix for a template field can be elided if `name` matches the right-most selector (i.e., `${code}` is same the as `${field.code}` in a `field` or `${method.code}` in a `method`).

**Example: `log` decorator**
```js
decorator log {
  class constructor {
    code {
      console.log("Created a new " + ${class.name});
      ${code}
    }
  }
  class method {
    code {
      console.log("Called " + ${class.name} + (${method.isStatic} ? "." : ".prototype.") + ${method.name});
      ${code}
    }
  }
  object method {
    code {
      console.log("Called " + ${method.name});
      ${code}
    }
  }
  function {
    code {
      console.log("Called " + ${function.name});
      ${code}
    }
  }
}

@log class C { @log method() {} }
// expands to:
// class C {
//   constructor() {
//     console.log("Created a new " + "C");
//   }
//   method() {
//     console.log("Called " + "C" + (false ? "." : ".prototype.") + "method");
//   }
// }
const c = new C(); // prints: "Created a new C"
c.method(); // prints: "Called C.prototype.method"

const x = { @log method() {} }
// expands to:
// const x = {
//   method() {
//     console.log("Called " + "method");
//   }
// };
x.method(); // prints: "Called method"

@log function foo() {}
// expands to:
// function foo() {
//   console.log("Called " + "foo");
// }
foo(); // prints "Called foo"

const y = @log () => {};
// expands to:
// const y = () => {
//   console.log("Called " + "y");
// };
y(); // prints "Called y";
```

**Example: `expose` decorator**
```js
decorator expose {
  class private field {
    get ${field.name}() { return this.#${field.name}; }
    set ${field.name}(value) { this.#${field.name} = value; }
  }
}

class C {
  @expose
  #x = 1;
}
// expands to:
// class C {
//   #x = 1;
//   get x() { return this.#x; }
//   set x(value) { this.#x = value; }
// }
const c = new C();
console.log(c.x); // prints: 1
```

**Comment by EisenbergEffect** [comment]
I like this direction! As I was trying to get my ideas down for the original, I started to have the idea of having a decorator block specify targets. This expands it to a much more explicit pattern matching approach, which makes a lot of sense.

I need to think through a few scenarios with this, but it seems like it can handle the use cases I have in mind at least, and possibly more than the legacy proposal, since you've covered object literals and functions as well.

@rbuckton Do you think all of these can be accomplished using the technique you outlined in issue #1 to handle isolated module configuration or would TS need to make decorators strictly not available in that mode?

**Comment by rbuckton** [comment]
I'm not sure if #1 is truly viable yet, so I can't answer that yet.

**Comment by EisenbergEffect** [comment]
I've got an update that incorporates the ideas above. Will close when I merge that in.

**Comment by EisenbergEffect** [comment]
Ok, closing, as the ideas are now merged.
